name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Add multiple commands to run if needed

            conan profile detect
            mkdir -p build
            cd build

            # gcc debug
            chmod +x ../scripts/make_debug_gcc.sh
            ../scripts/make_debug_gcc.sh
            ./Debug/tests/tests
            
            cd ..
            rm -rf build
            mkdir build
            cd build

            # gcc release
            chmod +x ../scripts/make_release_gcc.sh
            ../scripts/make_release_gcc.sh
            ./Release/tests/tests
            
            cd ..
            rm -rf build
            mkdir build
            cd build

            # clang debug
            chmod +x ../scripts/make_debug_clang.sh
            ../scripts/make_debug_clang.sh
            ./Debug/tests/tests
            
            cd ..
            rm -rf build
            mkdir build
            cd build

            # clang release
            chmod +x ../scripts/make_release_clang.sh
            ../scripts/make_release_clang.sh
            ./Release/tests/tests
            

